name: Github CI build

# GITHUB_REF_NAME in the form of release-$VERSION-$RELEASE-$EXTRA_NAME

on:
  push:
    tags:
      - release-**-**-**
  workflow_dispatch:

env:
  RELEASESDK: 5.0.0.43

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 20480
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-haskell: 'true'
        remove-android: 'true'
        remove-docker-images: 'true'
         
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Build mic
      run:  |
        export VERSION=$(echo $GITHUB_REF_NAME | cut -d "-" -f 2)
        export RELEASE=$(echo $GITHUB_REF_NAME | cut -d "-" -f 3)
        export EXTRA_NAME=-$(echo $GITHUB_REF_NAME | cut -d "-" -f 4-)
        chmod a+w $PWD
        ls -lh /
        pwd
        docker run -u root --rm --privileged --mount type=bind,src=$PWD,dst=/share --env-file env.list -e VERSION -e RELEASE -e EXTRA_NAME coderus/sailfishos-platform-sdk:$RELEASESDK /bin/bash -c "
            /share/scripts/create-image.sh --release $RELEASE --version $VERSION ;"

    - name: Update release
      run: |
        pwd
        ls
        export VERSION=$(echo $GITHUB_REF_NAME | cut -d "-" -f 2)
        export RELEASE=$(echo $GITHUB_REF_NAME | cut -d "-" -f 3)
        sudo tar -cvjSf sailfish-release-halium-krypton-$RELEASE-$VERSION.tar.bz2 -C ./build/mic/sfe*/Jolla*/ .
        gh release upload ${{ github.ref_name }} sailfish-release-halium-krypton-$RELEASE-$VERSION.tar.bz2 --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
